version: '3'

services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: todo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - api
    networks:
      - todo-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: todo-App
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - todo-network
    volumes:
      - ./app/src:/app/src

  api:
    build: ./api
    container_name: todo-api
    command: npm run dev
    restart: unless-stopped
    environment:
      - PORT=3001
      - MODE=development
#      - MONGO_URL=mongodb://db:27017/db
#    depends_on:
#      - db
    networks:
      - todo-network
    volumes:
      - ./api/src:/app/src

#  db:
#    image: mongo:latest
#    container_name: todo-db
#    restart: unless-stopped
#    volumes:
#      - mongodb:/data/db
#    networks:
#      - todo-network
#    ports:
#      - "27017:27017"

#volumes:
#  mongodb:

networks:
  todo-network:
    driver: bridge