version: '3'

services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: todo-nginx
    environment:
      - VIRTUAL_HOST=todo.andrewkozinsky.ru
      - LETSENCRYPT_HOST=todo.andrewkozinsky.ru
    volumes:
      - ./nginx/nginx.conf.serv:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - api

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: todo-App
    restart: unless-stopped
    command: serve -s build -l 3000

  api:
    build: ./api
    container_name: todo-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3001
      - MODE=production
      - MONGO_URL=mongodb://db:27017/db
    depends_on:
      - db
    volumes:
      - ./api/src:/App/src

  db:
    image: mongo:latest
    container_name: todo-db
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb:

networks:
  default:
    external:
      name: nginx-proxy