version: '3'

services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: todo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - api
    networks:
      - todo-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: todo-App
    restart: unless-stopped
    command: serve /application/dist -l 3000
    networks:
      - todo-network

  api:
    build: ./api
    container_name: todo-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3001
      - MODE=production
      - MONGO_URL=mongodb://db:27017/db
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: mongo:latest
    container_name: todo-db
    volumes:
      - mongodb:/data/db
    networks:
      - todo-network
    ports:
      - "27017:27017"

volumes:
  mongodb:

networks:
  todo-network:
    driver: bridge