FROM node:14.15.3-alpine3.12
WORKDIR /application
COPY . .

# Поставить все пакеты из package.json и сервер
RUN npm install && npm install -g serve

RUN mkdir dist

# Скопировать файл serve.json
COPY ./serve.json /application/dist

# Собрать пакет
RUN npm run build